name: IRCv3 Working Group
markdown: kramdown
highlighter: rouge
# baseurl: http://ircv3.net
liveurl: http://ircv3.net  # used in XML feeds
exclude:
  - README.md
gems:
  - jekyll-sitemap
sitemap:
  file: "/sitemap.xml"
collections:
  irc:
    output: true
